version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    # restart: always
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672