version: "3.1"

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    hostname: elasticsearch
    container_name: elasticsearch
    # restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch-cluster-qa
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: 256
        hard: 256

  kibana:
    image: kibana:7.9.3
    hostname: kibana
    container_name: kibana
    # restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    links:
      - elasticsearch

  logstash:
    image: logstash:7.9.3
    hostname: logstash
    container_name: logstash
    # restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5003:5003/udp
      - 5004:5004/tcp
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    links:
      - elasticsearch
    volumes:
      - ./:/config-dir
    command: logstash -f /config-dir/logstash.conf
    ulimits:
      memlock:
        soft: 256
        hard: 256